# Generated by Django 4.1.5 on 2023-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone_no',
            field=models.IntegerField(max_length=100),
        ),
    ]
