# Generated by Django 4.1.5 on 2023-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='username',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='no_of_books',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
