# Generated by Django 4.2.1 on 2023-05-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_username_alter_book_no_of_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pre_primary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='primary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='secondary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='senior_secondary',
            field=models.IntegerField(default=0),
        ),
    ]
