# Generated by Django 4.2.1 on 2023-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_pre_primary_book_primary_book_secondary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('query', models.TextField()),
                ('ngo', models.CharField(default='Null', max_length=100)),
                ('ngo_website', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('org', models.CharField(default='Null', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='city',
        ),
    ]
