# Generated by Django 4.2.1 on 2023-06-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contact_remove_book_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='ngo_website',
            new_name='website',
        ),
    ]
