# Generated by Django 4.2.1 on 2023-06-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_ngo_website_contact_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(max_length=600),
        ),
    ]
