# Generated by Django 4.2.1 on 2023-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_contact_type_alter_contact_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(default='Null', max_length=600),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
